// Seed the Question bank with starter questions for all topics
// Run: cd server && node seeds/seedQuestions.js

require('dotenv').config()
const mongoose = require('mongoose')
const Question = require('../models/Question')

const SEED_QUESTIONS = [
  // ─── DSA ───────────────────────────────────────────────────────────────
  { topic: 'DSA', subtopic: 'Arrays', difficulty: 'easy', type: 'mcq_single', question: 'What is the time complexity of accessing an element in an array by index?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], correct: 'O(1)', explanation: 'Arrays provide constant-time access by index since elements are stored in contiguous memory.', tags: ['dsa', 'arrays'] },
  { topic: 'DSA', subtopic: 'Arrays', difficulty: 'easy', type: 'mcq_single', question: 'Which data structure follows LIFO (Last In First Out) principle?', options: ['Queue', 'Stack', 'Array', 'Linked List'], correct: 'Stack', explanation: 'A stack follows LIFO — the last element pushed is the first one popped.', tags: ['dsa', 'stack'] },
  { topic: 'DSA', subtopic: 'Linked Lists', difficulty: 'easy', type: 'mcq_single', question: 'What is the time complexity of inserting at the beginning of a singly linked list?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correct: 'O(1)', explanation: 'Inserting at the head only requires updating the head pointer, which is O(1).', tags: ['dsa', 'linked-list'] },
  { topic: 'DSA', subtopic: 'Trees', difficulty: 'medium', type: 'mcq_single', question: 'What is the maximum number of nodes at level L of a binary tree?', options: ['2^L', '2^(L-1)', 'L^2', '2L'], correct: '2^L', explanation: 'At level L (root is level 0), the maximum number of nodes is 2^L.', tags: ['dsa', 'trees'] },
  { topic: 'DSA', subtopic: 'Trees', difficulty: 'medium', type: 'mcq_single', question: 'Which traversal of a Binary Search Tree gives elements in sorted order?', options: ['Preorder', 'Inorder', 'Postorder', 'Level order'], correct: 'Inorder', explanation: 'Inorder traversal (Left, Root, Right) of a BST visits nodes in ascending order.', tags: ['dsa', 'bst'] },
  { topic: 'DSA', subtopic: 'Graphs', difficulty: 'medium', type: 'mcq_single', question: 'Which algorithm is used to find the shortest path in an unweighted graph?', options: ['DFS', 'BFS', 'Dijkstra', 'Floyd-Warshall'], correct: 'BFS', explanation: 'BFS explores nodes level by level, naturally finding shortest paths in unweighted graphs.', tags: ['dsa', 'graphs'] },
  { topic: 'DSA', subtopic: 'Hash Maps', difficulty: 'easy', type: 'mcq_single', question: 'What is the average time complexity of HashMap lookup?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], correct: 'O(1)', explanation: 'Hash maps provide O(1) average lookup via hashing, though worst case is O(n).', tags: ['dsa', 'hashing'] },
  { topic: 'DSA', subtopic: 'Sorting', difficulty: 'medium', type: 'mcq_single', question: 'Which sorting algorithm has the best average-case time complexity?', options: ['Bubble Sort - O(n^2)', 'Merge Sort - O(n log n)', 'Selection Sort - O(n^2)', 'Insertion Sort - O(n^2)'], correct: 'Merge Sort - O(n log n)', explanation: 'Merge Sort consistently runs in O(n log n) for all cases.', tags: ['dsa', 'sorting'] },
  { topic: 'DSA', subtopic: 'Dynamic Programming', difficulty: 'hard', type: 'mcq_single', question: 'What is the time complexity of the longest common subsequence (LCS) problem using dynamic programming?', options: ['O(n)', 'O(n*m)', 'O(n^2)', 'O(2^n)'], correct: 'O(n*m)', explanation: 'The DP solution for LCS fills an n×m table, giving O(n*m) time complexity.', tags: ['dsa', 'dp'] },
  { topic: 'DSA', subtopic: 'Graphs', difficulty: 'hard', type: 'mcq_single', question: 'Which algorithm detects negative weight cycles in a graph?', options: ['Dijkstra', 'Bellman-Ford', 'Kruskal', 'Prim'], correct: 'Bellman-Ford', explanation: 'Bellman-Ford can detect negative weight cycles by running V-1 iterations and checking for further relaxation.', tags: ['dsa', 'graphs'] },

  // ─── OS ────────────────────────────────────────────────────────────────
  { topic: 'OS', subtopic: 'Processes', difficulty: 'easy', type: 'mcq_single', question: 'What is a process in an operating system?', options: ['A program in execution', 'A compiled code', 'A file on disk', 'A hardware component'], correct: 'A program in execution', explanation: 'A process is an instance of a program that is being executed, including its code, data, and resources.', tags: ['os', 'processes'] },
  { topic: 'OS', subtopic: 'Scheduling', difficulty: 'easy', type: 'mcq_single', question: 'Which CPU scheduling algorithm may cause starvation?', options: ['Round Robin', 'FCFS', 'Shortest Job First', 'Multilevel Queue'], correct: 'Shortest Job First', explanation: 'SJF can cause starvation for long processes since shorter ones keep getting priority.', tags: ['os', 'scheduling'] },
  { topic: 'OS', subtopic: 'Memory', difficulty: 'medium', type: 'mcq_single', question: 'What is thrashing in an operating system?', options: ['Excessive paging activity', 'CPU overheating', 'Disk fragmentation', 'Memory leak'], correct: 'Excessive paging activity', explanation: 'Thrashing occurs when too many processes compete for limited memory, causing constant page faults.', tags: ['os', 'memory'] },
  { topic: 'OS', subtopic: 'Deadlocks', difficulty: 'medium', type: 'mcq_single', question: 'Which condition is NOT necessary for a deadlock?', options: ['Mutual Exclusion', 'Hold and Wait', 'Preemption', 'Circular Wait'], correct: 'Preemption', explanation: 'The four necessary conditions are: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. Preemption prevents deadlock.', tags: ['os', 'deadlocks'] },
  { topic: 'OS', subtopic: 'Memory', difficulty: 'easy', type: 'mcq_single', question: 'What is virtual memory?', options: ['Extended RAM using disk space', 'Physical RAM only', 'Cache memory', 'GPU memory'], correct: 'Extended RAM using disk space', explanation: 'Virtual memory uses disk space as an extension of physical RAM, allowing larger address spaces.', tags: ['os', 'memory'] },
  { topic: 'OS', subtopic: 'Processes', difficulty: 'medium', type: 'mcq_single', question: 'What is the difference between a process and a thread?', options: ['Threads share address space, processes do not', 'Processes share address space, threads do not', 'They are identical', 'Threads run on separate CPUs'], correct: 'Threads share address space, processes do not', explanation: 'Threads within the same process share memory space, while separate processes have independent address spaces.', tags: ['os', 'threads'] },
  { topic: 'OS', subtopic: 'Synchronization', difficulty: 'hard', type: 'mcq_single', question: 'Which synchronization mechanism can lead to priority inversion?', options: ['Spinlock', 'Mutex', 'Semaphore', 'All of the above'], correct: 'All of the above', explanation: 'Priority inversion can occur with any locking mechanism when a low-priority task holds a lock needed by a high-priority task.', tags: ['os', 'sync'] },
  { topic: 'OS', subtopic: 'File Systems', difficulty: 'easy', type: 'mcq_single', question: 'What does an inode contain in a Unix file system?', options: ['File metadata and pointers', 'File name only', 'File content', 'User passwords'], correct: 'File metadata and pointers', explanation: 'An inode stores metadata (permissions, size, timestamps) and pointers to data blocks, but not the file name.', tags: ['os', 'filesystem'] },
  { topic: 'OS', subtopic: 'Scheduling', difficulty: 'medium', type: 'mcq_single', question: 'What is the time quantum in Round Robin scheduling?', options: ['Fixed time slice for each process', 'Total CPU time', 'Priority value', 'Context switch time'], correct: 'Fixed time slice for each process', explanation: 'The time quantum is the fixed duration each process runs before being preempted in Round Robin.', tags: ['os', 'scheduling'] },
  { topic: 'OS', subtopic: 'Memory', difficulty: 'hard', type: 'mcq_single', question: 'In the page replacement algorithm LRU, what does LRU stand for?', options: ['Last Recently Used', 'Least Recently Used', 'Lowest Required Usage', 'Latest Running Update'], correct: 'Least Recently Used', explanation: 'LRU replaces the page that has not been used for the longest time.', tags: ['os', 'paging'] },

  // ─── DBMS ──────────────────────────────────────────────────────────────
  { topic: 'DBMS', subtopic: 'SQL', difficulty: 'easy', type: 'mcq_single', question: 'Which SQL command is used to retrieve data from a database?', options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'], correct: 'SELECT', explanation: 'SELECT is the DML command used to query and retrieve data from tables.', tags: ['dbms', 'sql'] },
  { topic: 'DBMS', subtopic: 'Normalization', difficulty: 'medium', type: 'mcq_single', question: 'What does 3NF (Third Normal Form) eliminate?', options: ['Transitive dependencies', 'Partial dependencies', 'Multi-valued dependencies', 'All redundancy'], correct: 'Transitive dependencies', explanation: '3NF removes transitive dependencies — no non-prime attribute should depend on another non-prime attribute.', tags: ['dbms', 'normalization'] },
  { topic: 'DBMS', subtopic: 'Transactions', difficulty: 'easy', type: 'mcq_single', question: 'What does ACID stand for in databases?', options: ['Atomicity, Consistency, Isolation, Durability', 'Access, Control, Integration, Data', 'Automatic, Concurrent, Indexed, Distributed', 'Abstract, Compiled, Isolated, Durable'], correct: 'Atomicity, Consistency, Isolation, Durability', explanation: 'ACID properties ensure reliable transaction processing in databases.', tags: ['dbms', 'transactions'] },
  { topic: 'DBMS', subtopic: 'Indexing', difficulty: 'medium', type: 'mcq_single', question: 'What type of index is most efficient for range queries?', options: ['Hash Index', 'B-Tree Index', 'Bitmap Index', 'Full-text Index'], correct: 'B-Tree Index', explanation: 'B-Tree indexes maintain sorted order, making them ideal for range queries like BETWEEN.', tags: ['dbms', 'indexing'] },
  { topic: 'DBMS', subtopic: 'SQL', difficulty: 'easy', type: 'mcq_single', question: 'Which SQL clause is used to filter groups?', options: ['WHERE', 'HAVING', 'GROUP BY', 'ORDER BY'], correct: 'HAVING', explanation: 'HAVING filters groups created by GROUP BY, while WHERE filters individual rows.', tags: ['dbms', 'sql'] },
  { topic: 'DBMS', subtopic: 'Keys', difficulty: 'easy', type: 'mcq_single', question: 'What is a foreign key?', options: ['A key that references a primary key in another table', 'A unique identifier', 'An encrypted key', 'A composite key'], correct: 'A key that references a primary key in another table', explanation: 'A foreign key establishes a relationship between two tables by referencing the primary key of another table.', tags: ['dbms', 'keys'] },
  { topic: 'DBMS', subtopic: 'Transactions', difficulty: 'hard', type: 'mcq_single', question: 'Which isolation level prevents phantom reads?', options: ['Read Uncommitted', 'Read Committed', 'Repeatable Read', 'Serializable'], correct: 'Serializable', explanation: 'Serializable is the highest isolation level and prevents phantom reads by fully isolating transactions.', tags: ['dbms', 'isolation'] },
  { topic: 'DBMS', subtopic: 'SQL', difficulty: 'medium', type: 'mcq_single', question: 'What is the difference between INNER JOIN and LEFT JOIN?', options: ['LEFT JOIN includes unmatched rows from the left table', 'INNER JOIN includes all rows', 'LEFT JOIN is faster', 'There is no difference'], correct: 'LEFT JOIN includes unmatched rows from the left table', explanation: 'INNER JOIN returns only matching rows, while LEFT JOIN also includes non-matching rows from the left table with NULLs.', tags: ['dbms', 'joins'] },
  { topic: 'DBMS', subtopic: 'Normalization', difficulty: 'medium', type: 'mcq_single', question: 'What is denormalization?', options: ['Adding redundancy to improve read performance', 'Removing all tables', 'Encrypting data', 'Creating indexes'], correct: 'Adding redundancy to improve read performance', explanation: 'Denormalization introduces controlled redundancy to reduce expensive joins and improve query speed.', tags: ['dbms', 'normalization'] },
  { topic: 'DBMS', subtopic: 'SQL', difficulty: 'hard', type: 'mcq_single', question: 'What does a correlated subquery do?', options: ['References columns from the outer query', 'Runs independently', 'Returns multiple tables', 'Creates a temporary table'], correct: 'References columns from the outer query', explanation: 'A correlated subquery references columns from the outer query and is re-executed for each row of the outer query.', tags: ['dbms', 'sql'] },

  // ─── Networks ──────────────────────────────────────────────────────────
  { topic: 'Networks', subtopic: 'TCP/IP', difficulty: 'easy', type: 'mcq_single', question: 'Which layer of the OSI model does TCP operate on?', options: ['Network Layer', 'Transport Layer', 'Data Link Layer', 'Application Layer'], correct: 'Transport Layer', explanation: 'TCP operates at the Transport Layer (Layer 4), providing reliable data delivery.', tags: ['networks', 'tcp'] },
  { topic: 'Networks', subtopic: 'HTTP', difficulty: 'easy', type: 'mcq_single', question: 'What HTTP status code indicates "Not Found"?', options: ['200', '301', '404', '500'], correct: '404', explanation: '404 means the requested resource was not found on the server.', tags: ['networks', 'http'] },
  { topic: 'Networks', subtopic: 'DNS', difficulty: 'easy', type: 'mcq_single', question: 'What does DNS stand for?', options: ['Domain Name System', 'Data Network Service', 'Digital Naming Standard', 'Dynamic Node Server'], correct: 'Domain Name System', explanation: 'DNS translates human-readable domain names into IP addresses.', tags: ['networks', 'dns'] },
  { topic: 'Networks', subtopic: 'TCP/IP', difficulty: 'medium', type: 'mcq_single', question: 'What is the key difference between TCP and UDP?', options: ['TCP is connection-oriented, UDP is connectionless', 'UDP is slower than TCP', 'TCP uses less bandwidth', 'They are identical'], correct: 'TCP is connection-oriented, UDP is connectionless', explanation: 'TCP establishes a connection (3-way handshake) ensuring reliability, while UDP sends data without connection setup.', tags: ['networks', 'protocols'] },
  { topic: 'Networks', subtopic: 'Security', difficulty: 'medium', type: 'mcq_single', question: 'What does HTTPS use for encryption?', options: ['SSL/TLS', 'AES only', 'RSA only', 'Base64'], correct: 'SSL/TLS', explanation: 'HTTPS uses SSL/TLS protocols to encrypt communication between client and server.', tags: ['networks', 'security'] },
  { topic: 'Networks', subtopic: 'TCP/IP', difficulty: 'medium', type: 'mcq_single', question: 'How many steps are in the TCP 3-way handshake?', options: ['2 (SYN, ACK)', '3 (SYN, SYN-ACK, ACK)', '4 (SYN, SYN-ACK, ACK, FIN)', '1 (CONNECT)'], correct: '3 (SYN, SYN-ACK, ACK)', explanation: 'TCP establishes connections via: 1) Client sends SYN, 2) Server replies SYN-ACK, 3) Client sends ACK.', tags: ['networks', 'tcp'] },
  { topic: 'Networks', subtopic: 'Addressing', difficulty: 'easy', type: 'mcq_single', question: 'What is an IPv4 address composed of?', options: ['32 bits', '64 bits', '128 bits', '16 bits'], correct: '32 bits', explanation: 'IPv4 addresses are 32 bits long, typically shown as 4 octets (e.g., 192.168.1.1).', tags: ['networks', 'ip'] },
  { topic: 'Networks', subtopic: 'Routing', difficulty: 'hard', type: 'mcq_single', question: 'What is the purpose of BGP (Border Gateway Protocol)?', options: ['Inter-domain routing on the internet', 'Local network routing', 'Email delivery', 'DNS resolution'], correct: 'Inter-domain routing on the internet', explanation: 'BGP is the protocol that manages routing between autonomous systems (AS) across the internet.', tags: ['networks', 'routing'] },
  { topic: 'Networks', subtopic: 'HTTP', difficulty: 'medium', type: 'mcq_single', question: 'Which HTTP method is idempotent?', options: ['POST', 'GET', 'PATCH', 'None of these'], correct: 'GET', explanation: 'GET is idempotent — making the same request multiple times produces the same result without side effects.', tags: ['networks', 'http'] },
  { topic: 'Networks', subtopic: 'DNS', difficulty: 'medium', type: 'mcq_single', question: 'What type of DNS record maps a domain to an IP address?', options: ['A record', 'CNAME record', 'MX record', 'TXT record'], correct: 'A record', explanation: 'An A (Address) record maps a domain name to its corresponding IPv4 address.', tags: ['networks', 'dns'] },

  // ─── System Design ────────────────────────────────────────────────────
  { topic: 'System Design', subtopic: 'Scalability', difficulty: 'easy', type: 'mcq_single', question: 'What is horizontal scaling?', options: ['Adding more machines', 'Adding more RAM to one machine', 'Using faster CPU', 'Upgrading storage'], correct: 'Adding more machines', explanation: 'Horizontal scaling (scaling out) adds more servers to distribute load, unlike vertical scaling which upgrades a single server.', tags: ['system-design', 'scaling'] },
  { topic: 'System Design', subtopic: 'Caching', difficulty: 'easy', type: 'mcq_single', question: 'What is the primary benefit of caching?', options: ['Reduced latency and database load', 'More storage space', 'Better security', 'Simpler code'], correct: 'Reduced latency and database load', explanation: 'Caching stores frequently accessed data in fast storage (like Redis) to avoid repeated database queries.', tags: ['system-design', 'caching'] },
  { topic: 'System Design', subtopic: 'Load Balancing', difficulty: 'medium', type: 'mcq_single', question: 'Which load balancing algorithm distributes requests evenly in order?', options: ['Random', 'Round Robin', 'Least Connections', 'IP Hash'], correct: 'Round Robin', explanation: 'Round Robin distributes requests sequentially to each server in turn.', tags: ['system-design', 'load-balancing'] },
  { topic: 'System Design', subtopic: 'Databases', difficulty: 'medium', type: 'mcq_single', question: 'What does CAP theorem state?', options: ['A distributed system can only guarantee 2 of 3: Consistency, Availability, Partition Tolerance', 'All systems must be consistent', 'Caching Always Partitions', 'Concurrency And Parallelism are equal'], correct: 'A distributed system can only guarantee 2 of 3: Consistency, Availability, Partition Tolerance', explanation: 'The CAP theorem states that in a distributed system, you can only achieve two of three properties simultaneously.', tags: ['system-design', 'distributed'] },
  { topic: 'System Design', subtopic: 'Microservices', difficulty: 'medium', type: 'mcq_single', question: 'What is a key advantage of microservices over monolithic architecture?', options: ['Independent deployment and scaling', 'Simpler development', 'Less network overhead', 'Shared database'], correct: 'Independent deployment and scaling', explanation: 'Microservices allow each service to be developed, deployed, and scaled independently.', tags: ['system-design', 'architecture'] },
  { topic: 'System Design', subtopic: 'Messaging', difficulty: 'medium', type: 'mcq_single', question: 'What is a message queue used for?', options: ['Asynchronous communication between services', 'Storing user data', 'DNS resolution', 'Load balancing'], correct: 'Asynchronous communication between services', explanation: 'Message queues (like RabbitMQ, Kafka) decouple services and handle async communication.', tags: ['system-design', 'messaging'] },
  { topic: 'System Design', subtopic: 'CDN', difficulty: 'easy', type: 'mcq_single', question: 'What does a CDN (Content Delivery Network) do?', options: ['Serves content from geographically closer servers', 'Encrypts all traffic', 'Replaces databases', 'Manages DNS'], correct: 'Serves content from geographically closer servers', explanation: 'CDNs cache content at edge locations worldwide to reduce latency for users.', tags: ['system-design', 'cdn'] },
  { topic: 'System Design', subtopic: 'Databases', difficulty: 'hard', type: 'mcq_single', question: 'What is database sharding?', options: ['Splitting data across multiple databases', 'Creating backup copies', 'Encrypting data at rest', 'Indexing all columns'], correct: 'Splitting data across multiple databases', explanation: 'Sharding horizontally partitions data across multiple database instances to distribute load and storage.', tags: ['system-design', 'sharding'] },
  { topic: 'System Design', subtopic: 'Rate Limiting', difficulty: 'medium', type: 'mcq_single', question: 'Which algorithm is commonly used for API rate limiting?', options: ['Token Bucket', 'Binary Search', 'Dijkstra', 'MapReduce'], correct: 'Token Bucket', explanation: 'Token Bucket allows a fixed rate of requests with burst capacity, commonly used in API gateways.', tags: ['system-design', 'rate-limiting'] },
  { topic: 'System Design', subtopic: 'Consistency', difficulty: 'hard', type: 'mcq_single', question: 'What is eventual consistency?', options: ['All replicas converge to the same value over time', 'Immediate consistency everywhere', 'No consistency guarantee', 'Only one replica is consistent'], correct: 'All replicas converge to the same value over time', explanation: 'Eventual consistency guarantees that all replicas of the data will eventually reach the same state, given enough time.', tags: ['system-design', 'consistency'] },

  // ─── OOP ───────────────────────────────────────────────────────────────
  { topic: 'OOP', subtopic: 'Inheritance', difficulty: 'easy', type: 'mcq_single', question: 'What is inheritance in OOP?', options: ['A class acquiring properties of another class', 'Hiding implementation details', 'Multiple objects sharing memory', 'Compiling code faster'], correct: 'A class acquiring properties of another class', explanation: 'Inheritance allows a child class to inherit fields and methods from a parent class, promoting code reuse.', tags: ['oop', 'inheritance'] },
  { topic: 'OOP', subtopic: 'Polymorphism', difficulty: 'easy', type: 'mcq_single', question: 'What is method overloading?', options: ['Same method name with different parameters', 'Overriding a parent method', 'Creating abstract methods', 'Deleting methods'], correct: 'Same method name with different parameters', explanation: 'Method overloading (compile-time polymorphism) allows multiple methods with the same name but different parameter lists.', tags: ['oop', 'polymorphism'] },
  { topic: 'OOP', subtopic: 'Encapsulation', difficulty: 'easy', type: 'mcq_single', question: 'What is encapsulation?', options: ['Bundling data and methods, restricting direct access', 'Inheriting from multiple classes', 'Creating abstract classes', 'Using interfaces'], correct: 'Bundling data and methods, restricting direct access', explanation: 'Encapsulation wraps data and methods into a single unit (class) and uses access modifiers to control visibility.', tags: ['oop', 'encapsulation'] },
  { topic: 'OOP', subtopic: 'SOLID', difficulty: 'medium', type: 'mcq_single', question: 'What does the S in SOLID stand for?', options: ['Single Responsibility Principle', 'Structured Programming', 'System Design Principle', 'Safe Execution'], correct: 'Single Responsibility Principle', explanation: 'SRP states that a class should have only one reason to change — one responsibility.', tags: ['oop', 'solid'] },
  { topic: 'OOP', subtopic: 'Design Patterns', difficulty: 'medium', type: 'mcq_single', question: 'Which design pattern ensures only one instance of a class exists?', options: ['Factory', 'Singleton', 'Observer', 'Strategy'], correct: 'Singleton', explanation: 'The Singleton pattern restricts instantiation to a single object and provides a global access point.', tags: ['oop', 'patterns'] },
  { topic: 'OOP', subtopic: 'Abstraction', difficulty: 'easy', type: 'mcq_single', question: 'What is an abstract class?', options: ['A class that cannot be instantiated directly', 'A class with no methods', 'A class stored in memory', 'A compiled class'], correct: 'A class that cannot be instantiated directly', explanation: 'Abstract classes provide a template with abstract methods that must be implemented by subclasses.', tags: ['oop', 'abstraction'] },
  { topic: 'OOP', subtopic: 'Design Patterns', difficulty: 'hard', type: 'mcq_single', question: 'Which pattern defines a one-to-many dependency between objects?', options: ['Singleton', 'Factory', 'Observer', 'Adapter'], correct: 'Observer', explanation: 'The Observer pattern lets multiple observers subscribe to changes in a subject, notifying all when state changes.', tags: ['oop', 'patterns'] },
  { topic: 'OOP', subtopic: 'Polymorphism', difficulty: 'medium', type: 'mcq_single', question: 'What is the difference between method overloading and overriding?', options: ['Overloading is compile-time, overriding is runtime', 'They are the same', 'Overriding is compile-time', 'Overloading requires inheritance'], correct: 'Overloading is compile-time, overriding is runtime', explanation: 'Overloading resolves at compile time (same class, different params). Overriding resolves at runtime (subclass redefines parent method).', tags: ['oop', 'polymorphism'] },
  { topic: 'OOP', subtopic: 'SOLID', difficulty: 'hard', type: 'mcq_single', question: 'What does the Dependency Inversion Principle state?', options: ['High-level modules should depend on abstractions, not concretions', 'Classes should be open for extension', 'Use interfaces instead of classes', 'Always use dependency injection'], correct: 'High-level modules should depend on abstractions, not concretions', explanation: 'DIP states that both high-level and low-level modules should depend on abstractions, not concrete implementations.', tags: ['oop', 'solid'] },
  { topic: 'OOP', subtopic: 'Interfaces', difficulty: 'medium', type: 'mcq_single', question: 'What is the key difference between an interface and an abstract class?', options: ['Interfaces cannot have state, abstract classes can', 'Abstract classes cannot have methods', 'Interfaces support multiple inheritance of implementation', 'They are identical'], correct: 'Interfaces cannot have state, abstract classes can', explanation: 'Interfaces define contracts (methods only), while abstract classes can have both state (fields) and implemented methods.', tags: ['oop', 'interfaces'] },

  // ─── SQL ───────────────────────────────────────────────────────────────
  { topic: 'SQL', subtopic: 'Queries', difficulty: 'easy', type: 'mcq_single', question: 'Which SQL clause is used to sort results?', options: ['SORT BY', 'ORDER BY', 'ARRANGE BY', 'GROUP BY'], correct: 'ORDER BY', explanation: 'ORDER BY sorts the result set by one or more columns in ascending (ASC) or descending (DESC) order.', tags: ['sql', 'queries'] },
  { topic: 'SQL', subtopic: 'Aggregation', difficulty: 'easy', type: 'mcq_single', question: 'Which function returns the number of rows in a result set?', options: ['SUM()', 'COUNT()', 'AVG()', 'MAX()'], correct: 'COUNT()', explanation: 'COUNT() returns the number of rows that match a specified criteria.', tags: ['sql', 'aggregation'] },
  { topic: 'SQL', subtopic: 'Joins', difficulty: 'medium', type: 'mcq_single', question: 'What does a CROSS JOIN produce?', options: ['Cartesian product of both tables', 'Only matching rows', 'Unique rows only', 'An error'], correct: 'Cartesian product of both tables', explanation: 'CROSS JOIN produces every combination of rows from both tables (Cartesian product).', tags: ['sql', 'joins'] },
  { topic: 'SQL', subtopic: 'Subqueries', difficulty: 'medium', type: 'mcq_single', question: 'What is a subquery?', options: ['A query nested inside another query', 'A stored procedure', 'A database trigger', 'An index'], correct: 'A query nested inside another query', explanation: 'A subquery (inner query) is embedded within another SQL query and can be used in SELECT, FROM, or WHERE clauses.', tags: ['sql', 'subqueries'] },
  { topic: 'SQL', subtopic: 'DDL', difficulty: 'easy', type: 'mcq_single', question: 'Which SQL command creates a new table?', options: ['CREATE TABLE', 'NEW TABLE', 'MAKE TABLE', 'ADD TABLE'], correct: 'CREATE TABLE', explanation: 'CREATE TABLE is a DDL command that defines a new table structure in the database.', tags: ['sql', 'ddl'] },
  { topic: 'SQL', subtopic: 'Constraints', difficulty: 'medium', type: 'mcq_single', question: 'What does the UNIQUE constraint ensure?', options: ['All values in a column are different', 'Column cannot be NULL', 'Column has a default value', 'Column is indexed'], correct: 'All values in a column are different', explanation: 'UNIQUE ensures no duplicate values exist in the specified column(s).', tags: ['sql', 'constraints'] },
  { topic: 'SQL', subtopic: 'Window Functions', difficulty: 'hard', type: 'mcq_single', question: 'What does ROW_NUMBER() do?', options: ['Assigns a unique sequential integer to rows within a partition', 'Counts total rows', 'Returns the row type', 'Creates a new column'], correct: 'Assigns a unique sequential integer to rows within a partition', explanation: 'ROW_NUMBER() assigns a unique number to each row within a partition, starting from 1 based on the ORDER BY.', tags: ['sql', 'window'] },
  { topic: 'SQL', subtopic: 'Transactions', difficulty: 'medium', type: 'mcq_single', question: 'What does ROLLBACK do?', options: ['Undoes changes made in the current transaction', 'Saves all changes', 'Creates a savepoint', 'Deletes the table'], correct: 'Undoes changes made in the current transaction', explanation: 'ROLLBACK reverses all changes made since the last COMMIT or beginning of the transaction.', tags: ['sql', 'transactions'] },
  { topic: 'SQL', subtopic: 'Performance', difficulty: 'hard', type: 'mcq_single', question: 'What is an EXPLAIN plan used for?', options: ['Analyzing query execution strategy', 'Creating documentation', 'Backing up data', 'Encrypting queries'], correct: 'Analyzing query execution strategy', explanation: 'EXPLAIN shows the execution plan the database optimizer chooses, helping identify performance bottlenecks.', tags: ['sql', 'performance'] },
  { topic: 'SQL', subtopic: 'DML', difficulty: 'easy', type: 'mcq_single', question: 'Which command removes all rows from a table without logging individual row deletions?', options: ['DELETE', 'TRUNCATE', 'DROP', 'REMOVE'], correct: 'TRUNCATE', explanation: 'TRUNCATE removes all rows efficiently without logging individual deletions, and cannot be rolled back in some DBMS.', tags: ['sql', 'dml'] },

  // ─── Aptitude ──────────────────────────────────────────────────────────
  { topic: 'Aptitude', subtopic: 'Number Series', difficulty: 'easy', type: 'mcq_single', question: 'What comes next: 2, 4, 8, 16, __?', options: ['24', '32', '20', '28'], correct: '32', explanation: 'Each number is doubled: 2×2=4, 4×2=8, 8×2=16, 16×2=32.', tags: ['aptitude', 'series'] },
  { topic: 'Aptitude', subtopic: 'Percentages', difficulty: 'easy', type: 'mcq_single', question: 'What is 25% of 200?', options: ['25', '50', '75', '100'], correct: '50', explanation: '25% of 200 = (25/100) × 200 = 50.', tags: ['aptitude', 'percentages'] },
  { topic: 'Aptitude', subtopic: 'Profit & Loss', difficulty: 'medium', type: 'mcq_single', question: 'If CP=800 and SP=1000, what is the profit percentage?', options: ['20%', '25%', '30%', '15%'], correct: '25%', explanation: 'Profit = 1000-800 = 200. Profit% = (200/800)×100 = 25%.', tags: ['aptitude', 'profit-loss'] },
  { topic: 'Aptitude', subtopic: 'Time & Work', difficulty: 'medium', type: 'mcq_single', question: 'If A can complete work in 10 days and B in 15 days, how many days together?', options: ['5 days', '6 days', '8 days', '12 days'], correct: '6 days', explanation: 'A rate=1/10, B rate=1/15. Combined=1/10+1/15=5/30=1/6. Together=6 days.', tags: ['aptitude', 'time-work'] },
  { topic: 'Aptitude', subtopic: 'Probability', difficulty: 'easy', type: 'mcq_single', question: 'What is the probability of getting heads in a single coin toss?', options: ['1/4', '1/3', '1/2', '1'], correct: '1/2', explanation: 'A fair coin has 2 equally likely outcomes, so P(heads) = 1/2.', tags: ['aptitude', 'probability'] },
  { topic: 'Aptitude', subtopic: 'Speed & Distance', difficulty: 'medium', type: 'mcq_single', question: 'A train travels 120 km in 2 hours. What is its speed?', options: ['40 km/h', '50 km/h', '60 km/h', '80 km/h'], correct: '60 km/h', explanation: 'Speed = Distance/Time = 120/2 = 60 km/h.', tags: ['aptitude', 'speed'] },
  { topic: 'Aptitude', subtopic: 'Averages', difficulty: 'easy', type: 'mcq_single', question: 'What is the average of 10, 20, 30, 40, 50?', options: ['25', '30', '35', '40'], correct: '30', explanation: 'Average = (10+20+30+40+50)/5 = 150/5 = 30.', tags: ['aptitude', 'averages'] },
  { topic: 'Aptitude', subtopic: 'Permutations', difficulty: 'hard', type: 'mcq_single', question: 'How many ways can 5 people be arranged in a line?', options: ['25', '60', '120', '720'], correct: '120', explanation: '5! = 5×4×3×2×1 = 120 arrangements.', tags: ['aptitude', 'permutations'] },
  { topic: 'Aptitude', subtopic: 'Ratios', difficulty: 'medium', type: 'mcq_single', question: 'If A:B = 3:5 and B:C = 2:3, what is A:C?', options: ['2:5', '6:15', '3:3', '1:5'], correct: '2:5', explanation: 'A:B=3:5, B:C=2:3. Make B equal: A:B=6:10, B:C=10:15. So A:C=6:15=2:5.', tags: ['aptitude', 'ratios'] },
  { topic: 'Aptitude', subtopic: 'Simple Interest', difficulty: 'easy', type: 'mcq_single', question: 'What is the simple interest on Rs 1000 at 10% for 2 years?', options: ['Rs 100', 'Rs 200', 'Rs 150', 'Rs 250'], correct: 'Rs 200', explanation: 'SI = P×R×T/100 = 1000×10×2/100 = Rs 200.', tags: ['aptitude', 'interest'] },

  // ─── Verbal ────────────────────────────────────────────────────────────
  { topic: 'Verbal', subtopic: 'Synonyms', difficulty: 'easy', type: 'mcq_single', question: 'Choose the synonym of "Abundant":', options: ['Scarce', 'Plentiful', 'Meager', 'Rare'], correct: 'Plentiful', explanation: 'Abundant means existing in large quantities, which is synonymous with plentiful.', tags: ['verbal', 'synonyms'] },
  { topic: 'Verbal', subtopic: 'Antonyms', difficulty: 'easy', type: 'mcq_single', question: 'Choose the antonym of "Diligent":', options: ['Hardworking', 'Lazy', 'Careful', 'Persistent'], correct: 'Lazy', explanation: 'Diligent means hardworking and careful. Its opposite is lazy.', tags: ['verbal', 'antonyms'] },
  { topic: 'Verbal', subtopic: 'Grammar', difficulty: 'easy', type: 'mcq_single', question: 'Choose the correct sentence:', options: ['He go to school daily', 'He goes to school daily', 'He going to school daily', 'He gone to school daily'], correct: 'He goes to school daily', explanation: 'Third person singular (He) requires "goes" in simple present tense.', tags: ['verbal', 'grammar'] },
  { topic: 'Verbal', subtopic: 'Vocabulary', difficulty: 'medium', type: 'mcq_single', question: 'What does "Pragmatic" mean?', options: ['Idealistic', 'Practical and realistic', 'Emotional', 'Theoretical'], correct: 'Practical and realistic', explanation: 'Pragmatic means dealing with things sensibly and realistically.', tags: ['verbal', 'vocabulary'] },
  { topic: 'Verbal', subtopic: 'Reading Comprehension', difficulty: 'medium', type: 'mcq_single', question: 'The main purpose of a topic sentence is to:', options: ['Summarize the paragraph', 'State the main idea', 'Provide evidence', 'Conclude the argument'], correct: 'State the main idea', explanation: 'A topic sentence introduces the main idea that the rest of the paragraph develops.', tags: ['verbal', 'reading'] },
  { topic: 'Verbal', subtopic: 'Analogies', difficulty: 'medium', type: 'mcq_single', question: 'Book : Pages :: Tree : ?', options: ['Forest', 'Leaves', 'Wood', 'Root'], correct: 'Leaves', explanation: 'A book is made up of pages, just as a tree is made up of leaves.', tags: ['verbal', 'analogies'] },
  { topic: 'Verbal', subtopic: 'Sentence Correction', difficulty: 'medium', type: 'mcq_single', question: 'Identify the error: "Neither of the students have completed their assignment."', options: ['Neither', 'have (should be has)', 'students', 'their'], correct: 'have (should be has)', explanation: '"Neither" is singular and requires "has" instead of "have".', tags: ['verbal', 'correction'] },
  { topic: 'Verbal', subtopic: 'Idioms', difficulty: 'hard', type: 'mcq_single', question: 'What does "Bite the bullet" mean?', options: ['Eat something hard', 'Endure a painful situation bravely', 'Shoot a gun', 'Make a mistake'], correct: 'Endure a painful situation bravely', explanation: 'This idiom means to face a difficult or unpleasant situation with courage.', tags: ['verbal', 'idioms'] },
  { topic: 'Verbal', subtopic: 'Grammar', difficulty: 'easy', type: 'mcq_single', question: 'Which is a collective noun?', options: ['Happiness', 'Flock', 'Running', 'Beautiful'], correct: 'Flock', explanation: 'Flock is a collective noun referring to a group of birds.', tags: ['verbal', 'grammar'] },
  { topic: 'Verbal', subtopic: 'Vocabulary', difficulty: 'hard', type: 'mcq_single', question: 'What does "Ephemeral" mean?', options: ['Permanent', 'Lasting a very short time', 'Beautiful', 'Mysterious'], correct: 'Lasting a very short time', explanation: 'Ephemeral means lasting for a very short period of time.', tags: ['verbal', 'vocabulary'] },

  // ─── HR ────────────────────────────────────────────────────────────────
  { topic: 'HR', subtopic: 'Behavioral', difficulty: 'easy', type: 'mcq_single', question: 'What should you emphasize most in "Tell me about yourself"?', options: ['Personal hobbies', 'Professional background relevant to the role', 'Family details', 'Political views'], correct: 'Professional background relevant to the role', explanation: 'Focus on your professional experience, skills, and how they align with the role being discussed.', tags: ['hr', 'behavioral'] },
  { topic: 'HR', subtopic: 'Behavioral', difficulty: 'easy', type: 'mcq_single', question: 'What is the STAR method in interviews?', options: ['Situation, Task, Action, Result', 'Start, Try, Attempt, Retry', 'Study, Test, Analyze, Report', 'Set, Target, Achieve, Review'], correct: 'Situation, Task, Action, Result', explanation: 'STAR is a structured method to answer behavioral questions: describe the Situation, Task, Action taken, and Result.', tags: ['hr', 'star'] },
  { topic: 'HR', subtopic: 'Teamwork', difficulty: 'medium', type: 'mcq_single', question: 'When asked about a conflict with a teammate, the best approach is to:', options: ['Blame the teammate', 'Describe how you resolved it constructively', 'Say you never had conflicts', 'Refuse to answer'], correct: 'Describe how you resolved it constructively', explanation: 'Employers want to see conflict resolution skills — focus on how you communicated and reached a solution.', tags: ['hr', 'teamwork'] },
  { topic: 'HR', subtopic: 'Strengths', difficulty: 'easy', type: 'mcq_single', question: 'How should you answer "What is your weakness?"', options: ['Say you have none', 'Mention a genuine weakness and how you are improving', 'Criticize previous employers', 'Say you work too hard'], correct: 'Mention a genuine weakness and how you are improving', explanation: 'Be honest about a real weakness but demonstrate self-awareness and active steps to improve.', tags: ['hr', 'strengths'] },
  { topic: 'HR', subtopic: 'Communication', difficulty: 'medium', type: 'mcq_single', question: 'What percentage of communication is non-verbal?', options: ['10%', '30%', '55%', '93%'], correct: '93%', explanation: 'According to Mehrabian, 93% of communication is non-verbal (55% body language + 38% tone of voice).', tags: ['hr', 'communication'] },
  { topic: 'HR', subtopic: 'Leadership', difficulty: 'medium', type: 'mcq_single', question: 'Which leadership style involves team participation in decisions?', options: ['Autocratic', 'Democratic', 'Laissez-faire', 'Transactional'], correct: 'Democratic', explanation: 'Democratic leadership involves team members in the decision-making process.', tags: ['hr', 'leadership'] },
  { topic: 'HR', subtopic: 'Goals', difficulty: 'easy', type: 'mcq_single', question: 'What does SMART goals stand for?', options: ['Specific, Measurable, Achievable, Relevant, Time-bound', 'Simple, Modern, Active, Real, Tested', 'Structured, Major, Actionable, Reliable, Trackable', 'Strategic, Meaningful, Ambitious, Realistic, Timely'], correct: 'Specific, Measurable, Achievable, Relevant, Time-bound', explanation: 'SMART is a framework for setting clear and attainable goals.', tags: ['hr', 'goals'] },
  { topic: 'HR', subtopic: 'Salary', difficulty: 'hard', type: 'mcq_single', question: 'When asked about salary expectations, the best approach is:', options: ['Name the lowest number possible', 'Research market rates and give a range', 'Refuse to discuss', 'Ask for the maximum'], correct: 'Research market rates and give a range', explanation: 'Research industry standards and provide a reasonable range that reflects your experience and the market.', tags: ['hr', 'negotiation'] },
  { topic: 'HR', subtopic: 'Culture', difficulty: 'medium', type: 'mcq_single', question: 'Why do companies ask "Why do you want to work here?"', options: ['To test your research and genuine interest', 'To waste time', 'To confuse candidates', 'It is just a formality'], correct: 'To test your research and genuine interest', explanation: 'This question assesses whether you have researched the company and have genuine motivation beyond just a paycheck.', tags: ['hr', 'culture'] },
  { topic: 'HR', subtopic: 'Ethics', difficulty: 'medium', type: 'mcq_single', question: 'If an interviewer asks an illegal question (e.g., about religion), you should:', options: ['Answer it honestly', 'Politely redirect to your qualifications', 'Leave immediately', 'Report them to the police'], correct: 'Politely redirect to your qualifications', explanation: 'Professionally redirect the conversation to focus on your qualifications and suitability for the role.', tags: ['hr', 'ethics'] },
]

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/kai'
  await mongoose.connect(uri.includes('mongodb+srv') ? 'mongodb://localhost:27017/kai' : uri)
  
  const existing = await Question.countDocuments()
  console.log(`Existing questions: ${existing}`)
  
  let inserted = 0
  for (const q of SEED_QUESTIONS) {
    try {
      await Question.create(q)
      inserted++
    } catch (e) {
      // Skip duplicates
    }
  }
  
  const total = await Question.countDocuments()
  console.log(`Inserted ${inserted} new questions. Total: ${total}`)
  
  const topics = await Question.distinct('topic')
  for (const t of topics) {
    const count = await Question.countDocuments({ topic: t })
    console.log(`  ${t}: ${count} questions`)
  }
  
  await mongoose.disconnect()
  process.exit(0)
}

seed().catch(e => { console.error(e); process.exit(1) })
